### ISSUE TITLE
Support margin account on Fidelity

### ISSUE THREAD

**Issue by Flouzr** [NelsonDane/auto-rsa#108]
Currently if you have multiple accounts on Fidelity (one of such being a Margin account), you receive an error when purchasing a penny stock:
```
Fidelity .... : "DID NOT COMPLETE! 
Either this account does not have enough shares, or an order is already pending."
```

This is most likely due to "Margin" being the default payment type during the limit order instead of "Cash" and that type of order does not work on stock purchases that are to low in total order price.

I'm thinking toss it in the `.env` as an option as having it in the command could be ugly. This may be unwanted though as you one could want margin buys on some accounts and not others for some reason? If one is solely using this for RSA though, cash would be the preferred option as most buys are under $1.

If I have time I'll open a PR to fix this but in the meantime I want to put this out there. (great work on auto-rsa btw 😄 )

**Comment by NelsonDane** [comment]
Thanks for the feedback and thoughts! The way that the bot currently works is that it checks the stock price, and then determines whether a limit order or market order is needed. In the project's current form, there are no options for doing different types of trades per account so there shouldn't be a situation where you'd only want margin buys on certain accounts but not others. 

I don't have a margin account to test this with, but I think the best path forward would be to have the script only do cash-type buys, rather than adding another option to `.env`. However, if margin buys are something that you or others would really like then I'm sure that there's a good way to add support for them :)

**Comment by Flouzr** [comment]
> @Flouzr do you have a screenshot where margin acct allows you to pick between the two? Are you able to include the HTML's source page in a zip file that would have the drop down form values?

Do you need the floating menu html or the full-page trading html?

**Comment by Flouzr** [comment]
[margin-html.zip](https://github.com/NelsonDane/auto-rsa/files/13404913/margin-html.zip)
Here is the html and some pics of the floating menu. In the html around around line 197 is the margin selection html. If you need the full page order html just let me know.

**Comment by NelsonDane** [comment]
Thanks @Flouzr. I can add a check for the existence of `tradetype-cash` and switch to it if it exists. I don't have a margin account to test this with but i can at least get a branch upsoon so we can start solving the problem

**Comment by NelsonDane** [comment]
@Flouzr So sorry this took so long, I got busy with work/school. I pushed a change to the branch [auto-rsa/develop-fidelity](https://github.com/NelsonDane/auto-rsa/tree/develop-fidelity). If you could pull that and test it out that would be great. It should check for the existence of the element ID `tradetype-cash`, and if found, click it. If this doesn't fix it, please comment or send me an email and I can add you on Discord for easier communications.

**Comment by Flouzr** [comment]
@NelsonDane no worries, thanks for adding this! Currently away for the holidays so I'll test this out when I'm back. Enjoy your time off from school as well as the holidays!

**Comment by Flouzr** [comment]
@NelsonDane Updated my docker image and successfully bought shares on the margin account! I checked and I see them in the account as well. Looks like it should be good to merge in! I appreciate the help. Hope you're enjoying the holidays/time off!

**Comment by NelsonDane** [comment]
That's awesome to hear, glad it worked first try haha. I hope you're having a wonderful holiday season as well :)
