### ISSUE TITLE
Error when logging into Schwab

### ISSUE THREAD

**Issue by Sabermoose19** [NelsonDane/auto-rsa#149]
![image](https://github.com/NelsonDane/auto-rsa/assets/93809613/b4334894-d51f-4b8b-9478-f016b02f936e)
Apologies again, but when I try to login to schwab without 2fa this comes up.
I tried to install 2fa, however that also yielded an error of unable to get authentication state.

**Comment by NelsonDane** [comment]
Schwab defaults to SMS without 2FA i believe, which isn't supported. There are guides for setting up TOTP 2FA in the guides folder for setting stuff like that up.

**Comment by Sabermoose19** [comment]
Got it! Fixed. Thank you.
