### ISSUE TITLE
Fidelity issue

### ISSUE THREAD

**Issue by gusericson** [NelsonDane/auto-rsa#152]
I get the following error when attempting to do a dry run on fidelity. I just started using this and my other brokers work perfectly, thank you so much!

"Logging in to Fidelity...
Error getting Driver: Could not reach host. Are you offline?
Fidelity Error: Error: Unable to get driver
Traceback (most recent call last):
  File "C:\Users\ericson\Downloads\auto-rsa-main\auto-rsa-main\fidelityAPI.py", line 74, in fidelity_init
    raise Exception("Error: Unable to get driver")
Exception: Error: Unable to get driver"
File "C:\Users\ericson\Downloads\auto-rsa-main\auto-rsa-main\autoRSA.py", line 191, in <module>
    cliOrderObj.order_validate()
  File "C:\Users\ericson\Downloads\auto-rsa-main\auto-rsa-main\helperAPI.py", line 156, in order_validate
    raise ValueError("Logged In must be set")"

**Comment by NelsonDane** [comment]
I hate to say the obvious, but make sure that you're up to date and have a good internet connection 😅 

Assuming that, make sure that you have Microsoft Edge installed since Fidelity uses Selenium in Edge. It would also help to know what OS you're using (Windows has a lot of weird issues I haven't experienced on Mac/Linux)

**Comment by gusericson** [comment]
I don't believe it's an issue with connection as my other brokers work fine, and I have the script set to auto update (and just downloaded it last night). I do have edge installed, should've said this in the orignal post but I'm on Windows 10.

**Comment by gusericson** [comment]
I figured it out because the script worked for me on Mac once I downloaded edge. For some reason my edge isn't installed right or something on windows.

**Comment by NelsonDane** [comment]
I'm glad it worked on the Mac, hopefully, you can figure out the issue with Windows! Feel free to open other issues if (when) they arise or make a PR if you fix anything yourself :)
