### ISSUE TITLE
Error when running through docker

### ISSUE THREAD

**Issue by Sabermoose19** [NelsonDane/auto-rsa#206]
![image](https://github.com/NelsonDane/auto-rsa/assets/93809613/0ac71529-fee1-4c07-901e-8d35735b9247)

![image](https://github.com/NelsonDane/auto-rsa/assets/93809613/9be61e5b-60e5-49c1-8b13-dea28617b118)

I have had the bot running 24/7 for the past two weeks with no issues until today when I wake up and it's giving me these errors. I don't know what to do to fix this.

Watchtower boots up fine with no issues.

**Comment by NelsonDane** [comment]
Hello, this is an error that I accidently introduced yesterday. It was fixed last night, so please update the container and it should be back to normal :)
