### ISSUE TITLE
Order object will be corrupted to "sell 100 or 1000 - amount desired" if Webull sell fails.

### ISSUE THREAD

**Issue by terose73** [NelsonDane/auto-rsa#213]
If this line triggers an exception, the subsequent lines can't restore the order object. This results in corruption of **all** orders afterwards to be "sell 100 or 1000 - amount desired". This could cause inadvertent short sales.

https://github.com/NelsonDane/auto-rsa/blob/6e3925b718052f119af8af9a9c6f552cfe898985/webullAPI.py#L175

This could be resolved by moving these lines https://github.com/NelsonDane/auto-rsa/blob/6e3925b718052f119af8af9a9c6f552cfe898985/webullAPI.py#L177-L178 to a "finally" block in the try-except scope. I would also use the original order type instead of "buy" for the sell case.

**Comment by NelsonDane** [comment]
Awesome find, thanks!

Fixed in: 2d04fe55efbb99aa1b62c2f966987814caea2df5
