### ISSUE TITLE
Fidelity issues on docker 

### ISSUE THREAD

**Issue by gusericson** [NelsonDane/auto-rsa#221]
I've been running docker smoothly for 3ish months, but on Monday I started getting this error, all other brokers than Fidelity work perfectly. 

<img width="960" alt="Screenshot 2024-04-24 at 11 17 39 AM" src="https://github.com/NelsonDane/auto-rsa/assets/45617618/7ce984e3-cc0d-4622-9a08-325550968fc5">

**Comment by kdabas03** [comment]
I also got the same error.

**Comment by EClinick** [comment]
Same here

**Comment by NelsonDane** [comment]
After speaking in Discord, this is a combination of issues with Selenium, Docker, and Apple Silicon Macs. I did a lot of digging but still haven't found a solution.
