### ISSUE TITLE
Error logging into Fidelity

### ISSUE THREAD

**Issue by Flouzr** [NelsonDane/auto-rsa#245]
I noticed that when buying with _all_, Fidelity wasn't being listed anymore. This is the output from running `!rsa holdings fidelity`.

I've also doubt-checked that my username/pass is correct in the _.env_

![image](https://github.com/NelsonDane/auto-rsa/assets/3201104/3bd717b4-963b-4632-bf64-582abbd96c7f)

**Comment by Flouzr** [comment]
> Is this still happening?

Yeah, same thing. I also checked that my docker instance is up-to-date as well and my `.env` is of the required format.

**Comment by NelsonDane** [comment]
Hmm alright. When an error occurs, it should save a screenshot of what was on the screen when it crashed, which would help. It should be in the folder if run through the command line, or if it's in docker you can use the Docker GUI app or look up the commands to copy a file from the container. But knowing what it was looking at when it couldn't find the element would be a good first step. Just make sure to blot out any sensitive info of course

**Comment by Flouzr** [comment]
The two previous runs from earlier show the same thing. Looks like it's just sitting on the login screen. 

![fidelity-error-2024-06-05 16:52:05 547110](https://github.com/NelsonDane/auto-rsa/assets/3201104/03da4be0-2121-4bc9-ac8f-22e46e37b8d9)

**Comment by NelsonDane** [comment]
Hmm, that's interesting. Are you using an ARM-based PC by chance? A few others and I had the same issue maybe a month ago on M-series Macs and Raspberry PIs, but I pushed a fix for it that seemed to work. Make sure your `docker-compose.yml` looks just like [this](https://github.com/NelsonDane/auto-rsa/blob/main/docker-compose.yml), then run `docker compose pull` and `docker compose up -d`, just to be sure the docker container is up to date.

Otherwise, could you share your specs/OS?

**Comment by Flouzr** [comment]
It's an ThinkCentre M920q running an Intel(R) Core(TM) i5-8500T, so not ARM based. auto-rsa is running inside a Proxmox container, but it was previously without issue, so I don't think that's the reason.

![Screenshot_20240605_223557](https://github.com/NelsonDane/auto-rsa/assets/3201104/14fed102-0043-44ed-83f0-106d6ddac680)

**Comment by Flouzr** [comment]
So i figured it out. Holdings is reporting correct totals (albeit all shares show $0), but it's logging in so I'll try it out next week!

The issue was actually quite dumb. Mult-factor auth was on but it didn't become an issue until recently. Turning off multi-factor fixed the issue.
