### ISSUE TITLE
Commit 39f6399 for Setuptools bump to 70.1.0

### ISSUE THREAD

**Issue by Nohealz** [NelsonDane/auto-rsa#263]
Firstrade started having issues today not being able to login.

Rolled back the setuptools to `70.0.0`. Firstrade works again.

Here is what the traceback says, sorry it wasn't a verbatim copy+paste but it should do the trick.
```
File auto-rsa\firstradeAPI.py line 42, in firstrade_init
account_info = ft_account.FTAccountData(firstrade)

File site-packages\firstrade\account.py, line 183, in __init
self.account_statuses.append(account_status["data"])

KeyError: 'data'
```

I had to manually update the requirements.txt to match and get it to run. Here is what python script said on startup
```
Starting auto update...
UPDATE ERROR: Conflicting changes found. Please commit, stash, or remove your changes before updating.

Checking package versions...
All required packages are installed and up to date.

Running Discord bot from command line

Discord bot is started...
```

**Comment by NelsonDane** [comment]
Oh no, sorry you're having this issue. I tested it this morning with the new `setuptools` and Firstrade works for me in CLI and Docker, but I'll ask around and see if anyone is also having the issue. For now, I'd suggest trying a new Python venv and see if that's any different.

**Comment by Nohealz** [comment]
> Oh no, sorry you're having this issue. I tested it this morning with the new `setuptools` and Firstrade works for me in CLI and Docker, but I'll ask around and see if anyone is also having the issue. For now, I'd suggest trying a new Python venv and see if that's any different.

So the Python script method worked? I only tried it because another person told me it wasn’t working. Mine also wouldn’t log in. I’m not sure if anything else happened over the weekend but maybe I can upgrade and test it again tomorrow.

**Comment by NelsonDane** [comment]
Yep, I tried both the Python CLI script and the Docker container, and they both worked. I also checked with some other people and they reported the same.

**Comment by Nohealz** [comment]
Something went corrupt or wasn't able to update properly because I did a clean and fresh git pull, ran the requirements again and it updated a few libraries. Everything running so far.

**Comment by NelsonDane** [comment]
That's awesome to hear!
