### ISSUE TITLE
Fidelity Error: could not convert string to float: '0.00‡‡‡'

### ISSUE THREAD

**Issue by Nohealz** [NelsonDane/auto-rsa#268]
Feel like I'm creating too many of these :(

I know 2 other people that is seeing this error and not able to get Fidelity to work.

```
Warning: Account numbers, values, and types are not the same length! Using shortest length: 10
Fidelity Error: could not convert string to float: '0.00‡‡‡'
Traceback (most recent call last):
  File "C:\Users\_____\auto-rsa\fidelityAPI.py", line 224, in fidelity_account_info
    "balance": float(av),
               ^^^^^^^^^
ValueError: could not convert string to float: '0.00‡‡‡'

Fidelity Error: Fidelity 1: Error getting account info
Traceback (most recent call last):
  File "C:\Users\____\auto-rsa\fidelityAPI.py", line 165, in fidelity_init
    raise Exception(f"{name}: Error getting account info")
Exception: Fidelity 1: Error getting account info


Error: fidelity not logged in, skipping...
```

I'm going to have them add a line in the fidelityAPI.py after line 220 `.replace("‡", "")`
Let me know if you have any other suggestions and I'll let you know if that fixes it for them.

**Comment by Nohealz** [comment]
Adding that line after 220 did fix it for them. My guess it's from an older 401K account that they both have in there.

Worth pushing that in an update eventually but I am having them fix it manually for now.

**Comment by NelsonDane** [comment]
No worries :) 
If you already found a fix, could you make a pull request for it?

**Comment by Nohealz** [comment]
That's my first contribution to a git project so if I messed something up let me know.

What is needed to bring Sofi online?
