### ISSUE TITLE
Running into issues

### ISSUE THREAD

**Issue by geoxcaliber** [NelsonDane/auto-rsa#272]
Apologies for perhaps putting this in the wrong place, but I’m running into issues getting the bot to work. Is there any way I can contact you to ask a couple questions? Only Fennel is properly executing trades, the rest just aren’t working; using discord docker.

**Comment by PZES** [comment]
Can you please be more specific

**Comment by geoxcaliber** [comment]
After more troubleshooting, I got most to work except Vanguard. Does yours work there? the command holdings vanguard just returns a bunch of errors.
