### ISSUE TITLE
Bug: Leading 0s in getOTPCodeDiscord() get cut

### ISSUE THREAD

**Issue by matthew55** [NelsonDane/auto-rsa#282]
I am working on making an API for Ally using Selenium and everytime I call the function `getOTPCodeDiscord()` in `helperAPI.py` if my OTP code starts with any 0s, it is getting cut.

Example input: `001200`
What the bot sends to the website: `1200`

I am not getting any OTP code requests on any other brokers, so I can not verify if this is for every site, but I am imagining that it is. Can anyone else recreate this and confirm that this is a multi-site problem, and does anyone have any ideas on what could cause this?

**Comment by NelsonDane** [comment]
You're right, this is a bug. I just looked it up, but in Python when casting to an `int`, it removes leading zeroes. I'll push a fix for this shortly

**Comment by NelsonDane** [comment]
Should be fixed in `55f021d90573abf0120f4b97a8a7c6e0cd968cfb`

**Comment by matthew55** [comment]
Thank you, 55f021d fixed the issue.
